# 🗂️ NumPy – Numerical Computing Library 🔢


In [1]:

# 🔹 Quick Tips:
# - NumPy arrays are faster than Python lists
# - Use vectorized operations (no loops)
# - reshape() changes dimensions
# - Use NumPy for math & matrix operations


In [2]:

import numpy as np

# 1️⃣ Create NumPy Arrays 📦
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[1, 2], [3, 4]])
print(arr1)
print(arr2)


[1 2 3 4]
[[1 2]
 [3 4]]


In [3]:

# 2️⃣ Array Properties 🔍
print(arr1.ndim)     # Number of dimensions
print(arr1.shape)    # Shape of array
print(arr1.size)     # Total elements
print(arr1.dtype)    # Data type


1
(4,)
4
int64


In [4]:

# 3️⃣ Special Arrays ⚙️
zeros = np.zeros((2, 3))
ones = np.ones((3, 2))
identity = np.eye(3)
print(zeros)
print(ones)
print(identity)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:

# 4️⃣ Range & Random Arrays 🎯
nums = np.arange(1, 10, 2)
rand = np.random.rand(3, 3)
print(nums)
print(rand)


[1 3 5 7 9]
[[0.98154884 0.59095405 0.33351745]
 [0.48456256 0.24118045 0.69855748]
 [0.66042121 0.62099878 0.30381923]]


In [6]:

# 5️⃣ Array Operations ➕➖✖️➗
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)
print(a ** 2)


[5 7 9]
[ 4 10 18]
[1 4 9]


In [7]:

# 6️⃣ Indexing & Slicing ✂️
arr = np.array([10, 20, 30, 40, 50])
print(arr[1])
print(arr[1:4])


20
[20 30 40]


In [8]:

# 7️⃣ Reshape & Flatten 🔄
matrix = np.arange(1, 7).reshape(2, 3)
print(matrix)
print(matrix.flatten())


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [9]:

# 8️⃣ Statistical Functions 📊
data = np.array([10, 20, 30, 40, 50])
print(np.mean(data))
print(np.sum(data))
print(np.min(data))
print(np.max(data))
print(np.std(data))


30.0
150
10
50
14.142135623730951
